# VGGNet16 features extraction.

One of the key components to be able to create a GMVAE of the CXR14 dataset, is to be able to retrieve <br>
the VGGne16 features, just as how the paper. <br><br> "Deep Generative Classifiers for Thoracic Disease Diagnosis with Chest X-ray Images" has done. <br>
link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6651749/

In [1]:
 #Import necessary modules
import os
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torchvision.models as models
from torch.utils.data import DataLoader
from torchvision import transforms
plt.rcParams['figure.figsize'] = [20, 12]

### Set the path to here

Make sure the setup the paths properly!

In [2]:
#Path to assign tests (copy path directly)
test_path = r"D:\Python_Projects\CS236-Final-Proj\test"

#Set the path to this working directory
os.chdir(test_path)
print(os.getcwd())

import sys
#Append the path the src folder
sys.path.append(r'D:\Python_Projects\CS236-Final-Proj\src')

D:\Python_Projects\CS236-Final-Proj\test


### Import the necessary module for downloading

Note for this: EVERYTIME There is a change inside the download <br>
the changes inside the file would only be shown if the jupyter kernel is restarted. <br>


In [3]:
# Import the necessary modules
from utils import CXReader, DfReader

### Set the data path

In [4]:
# Create the data path
data_path = os.path.join(test_path, os.pardir, "data")

### Get the dataframes of the data
First, lets obtain the dataframes for the data and check that all metadata <br>
information has been set up properly. <br>

In [5]:
#Create a dataframe compiler
df_compiler = DfReader()

#set the path and retrieve the dataframes
df_compiler.set_folder_path(data_path)

#Get the dataframe holder and names
dfs_holder, dfs_names = df_compiler.get_dfs()

100%|██████████| 112124/112124 [00:00<00:00, 505359.12it/s]

The file: miccai2023_nih-cxr-lt_labels_test.csv has been retrieved
The file: miccai2023_nih-cxr-lt_labels_train.csv has been retrieved
The file: miccai2023_nih-cxr-lt_labels_val.csv has been retrieved


In [6]:
# Get the device if cuda or not
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

#Define a transformations for the VGGnet16 (requires a 224,224)
transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
])

#Create datasets and dataloaders
test_dataset = CXReader(data_path=data_path, dataframe=dfs_holder[0], transform=transform, device=device)
train_dataset = CXReader(data_path=data_path, dataframe=dfs_holder[1], transform=transform,device=device)
val_dataset = CXReader(data_path=data_path, dataframe=dfs_holder[2], transform=transform, device=device)

#Sampled images from train to see single shape
samp3_image, label3 = train_dataset[1]
print("Shape of a single image and its labels")
print(f"Image: {samp3_image.shape}, labels: {label3.shape}")

#With batch size of 32, and shuffle true, and num workers = 4
batch_size = 32

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False,  num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False,  num_workers=2)

#Iterate inside a batch
for idx, batch in enumerate(train_loader):
    print(f"batch number: {idx}")
    images, labels = batch
    print("Shape of batch of images and labels")
    print(f"Images: {images.shape}, labels: {labels.shape}")
    if idx == 5:
        print("It can iterate through all batches")
        break

Shape of a single image and its labels
Image: torch.Size([3, 224, 224]), labels: torch.Size([20])
batch number: 0
Shape of batch of images and labels
Images: torch.Size([32, 3, 224, 224]), labels: torch.Size([32, 20])
batch number: 1
Shape of batch of images and labels
Images: torch.Size([32, 3, 224, 224]), labels: torch.Size([32, 20])
batch number: 2
Shape of batch of images and labels
Images: torch.Size([32, 3, 224, 224]), labels: torch.Size([32, 20])
batch number: 3
Shape of batch of images and labels
Images: torch.Size([32, 3, 224, 224]), labels: torch.Size([32, 20])
batch number: 4
Shape of batch of images and labels
Images: torch.Size([32, 3, 224, 224]), labels: torch.Size([32, 20])
batch number: 5
Shape of batch of images and labels
Images: torch.Size([32, 3, 224, 224]), labels: torch.Size([32, 20])
It can iterate through all batches


### Print an image and see the output

In [9]:
print(samp3_image)
print(samp3_image.shape)

tensor([[[0.8000, 0.7961, 0.7843,  ..., 0.7686, 0.7725, 0.7569],
         [0.7961, 0.7882, 0.7725,  ..., 0.7490, 0.7608, 0.7373],
         [0.7922, 0.7804, 0.7686,  ..., 0.7333, 0.7451, 0.7216],
         ...,
         [0.2745, 0.1255, 0.0549,  ..., 0.0392, 0.0118, 0.0000],
         [0.2745, 0.1255, 0.0549,  ..., 0.0353, 0.0078, 0.0000],
         [0.2784, 0.1255, 0.0549,  ..., 0.0353, 0.0078, 0.0000]],

        [[0.8000, 0.7961, 0.7843,  ..., 0.7686, 0.7725, 0.7569],
         [0.7961, 0.7882, 0.7725,  ..., 0.7490, 0.7608, 0.7373],
         [0.7922, 0.7804, 0.7686,  ..., 0.7333, 0.7451, 0.7216],
         ...,
         [0.2745, 0.1255, 0.0549,  ..., 0.0392, 0.0118, 0.0000],
         [0.2745, 0.1255, 0.0549,  ..., 0.0353, 0.0078, 0.0000],
         [0.2784, 0.1255, 0.0549,  ..., 0.0353, 0.0078, 0.0000]],

        [[0.8000, 0.7961, 0.7843,  ..., 0.7686, 0.7725, 0.7569],
         [0.7961, 0.7882, 0.7725,  ..., 0.7490, 0.7608, 0.7373],
         [0.7922, 0.7804, 0.7686,  ..., 0.7333, 0.7451, 0.

### Obtain the vgg16_model features and set to eval

In [11]:
class VGGEncoder(torch.nn.Module):
    def __init__(self, pretrained=True):
        super(VGGEncoder, self).__init__()

        # Load pre-trained VGG16 model
        vgg16_model = models.vgg16(pretrained=pretrained)

        # Use only the features part and remove the classifier
        self.features = vgg16_model.features

        # Set to evaluation mode if not fine-tuning
        if not pretrained:
            self.features.eval()

    def forward(self, x):
        return self.features(x)

# Example usage
# For fine-tuning
#encoder_finetune = VGGEncoder(pretrained=False)
#encoder_finetune.train()

# For inference
encoder_inference = VGGEncoder(pretrained=True)
encoder_inference.eval()

#Print output and output features
output_features = encoder_inference(samp3_image)
print(output_features)
print(output_features.shape)

d:\Python_Projects\CS236-Final-Proj\venv\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
d:\Python_Projects\CS236-Final-Proj\venv\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.1371, 0.3649,  ..., 0.0929, 0.2825, 0.0000],
         [0.0000, 0.1291, 0.3101,  ..., 0.2486, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.6302,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.1466,  ..., 0.0335, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0788, 0.0000,  ..., 0.0000, 0.0000, 0.1012],
         [0.0000, 0.2479, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.

### Now that we have seen the VGG16 layer.
Lets implement the solution where we flat the feature vector to a 1x1xD vector. <br>
just as how the paper does it.

In [36]:
class TransitionLayer(nn.Module):
    def __init__(self, input_channels, output_channels):
        super(TransitionLayer, self).__init__()
        
        # Convolutional layer with kernel size 1x1
        self.conv1x1 = nn.Conv2d(input_channels, output_channels, kernel_size=1)
        
        # Batch normalization
        self.batch_norm = nn.BatchNorm2d(output_channels)
        
        # ReLU activation
        self.relu = nn.ReLU(inplace=True)
        
        # Max pooling with kernel size equal to the feature map size
        self.max_pool = nn.MaxPool2d(kernel_size=7)

    def forward(self, x):
        # Apply operations sequentially
        x = self.conv1x1(x)
        x = self.batch_norm(x)
        x = self.relu(x)
        x = self.max_pool(x)
        return x

# Example usage
input_channels = 512
output_channels = 300 # D is the desired number of channels
transition_layer = TransitionLayer(input_channels, output_channels)

# Assuming input_tensor is of size (batch_size, 512, 7, 7)
input_tensor = torch.randn(3, input_channels, 7, 7)

# Apply the transition layer
output = transition_layer(input_tensor)

# Print the shape of the final feature vector
print(output.shape)
print(output)

torch.Size([3, 300, 1, 1])
tensor([[[[1.9504]],

         [[2.8891]],

         [[2.0695]],

         [[2.5180]],

         [[2.1734]],

         [[2.2566]],

         [[1.7711]],

         [[2.1167]],

         [[2.3652]],

         [[1.6242]],

         [[2.0487]],

         [[1.9136]],

         [[1.9123]],

         [[2.0060]],

         [[2.7016]],

         [[2.7294]],

         [[2.6718]],

         [[2.2179]],

         [[1.9488]],

         [[1.9449]],

         [[2.2826]],

         [[1.8497]],

         [[2.1873]],

         [[1.3241]],

         [[2.9704]],

         [[2.4062]],

         [[3.1645]],

         [[1.9799]],

         [[1.5627]],

         [[2.3195]],

         [[2.0308]],

         [[2.5041]],

         [[2.2661]],

         [[2.4397]],

         [[2.0639]],

         [[1.9733]],

         [[2.4823]],

         [[2.3043]],

         [[2.3744]],

         [[2.2648]],

         [[2.5281]],

         [[1.8426]],

         [[2.3494]],

         [[1.9849]],

     

# BIIIIG. We know the feature space at the end would be 512, 7, 7. 
This means that, if we want to create an encoder that would take this; and convert it to a sampling gaussian representation <br>
we need to do the following:
1. Pass a VGGnet16 pretrained features at eval mode (option to pretrain it too) to 512, 7, 7.
2. Pass that VGGnet16 through a transition layer that would flat it to a num_channelsx 300 output (3 since RGB).
3. Use this to sample a mean and gaussian distribution uing homework codes to retrieve results.

### Create a function that would sample gaussian parameters.
Use functions from hw2 utils.py to do this.

In [13]:
from torch.nn import functional as F
def gaussian_parameters(h, dim=-1):
    """
    Converts generic real-valued representations into mean and variance
    parameters of a Gaussian distribution

    Args:
        h: tensor: (batch, ..., dim, ...): Arbitrary tensor
        dim: int: (): Dimension along which to split the tensor for mean and
            variance

    Returns:
        m: tensor: (batch, ..., dim / 2, ...): Mean
        v: tensor: (batch, ..., dim / 2, ...): Variance
    """
    m, h = torch.split(h, h.size(dim) // 2, dim=dim)
    v = F.softplus(h) + 1e-8
    return m, v